version: '3'
services:
  qdjr:
    build:
      context: .
      dockerfile: ./docker/nuxt/Dockerfile
    working_dir: /var/www/html/qdjr
    expose:
      - 3000
    container_name: qdjr
    volumes:
      - .:/var/www/html/qdjr
    network_mode: "host"
