// ESLint 9 flat config, generated by @nuxt/eslint.
//
// Replaces .eslintrc.js: ESLint 9 removed eslintrc support and the --ext flag,
// so `lint:js` is now a bare `eslint .`. The Nuxt module supplies the Vue and
// TypeScript setup that eslint-plugin-vue@7 (a Vue 2-era package extending
// vue3-recommended) and the standalone typescript-eslint packages used to.
import withNuxt from './.nuxt/eslint.config.mjs'
import prettier from 'eslint-config-prettier'

export default withNuxt(
  {
    ignores: [
      'node_modules',
      '.nuxt',
      '.output',
      '.data',
      'dist',
      'public',
      'test-results',
      'playwright-report',
      'pm2.config.js'
    ]
  },
  {
    rules: {
      // Carried over from the old config.
      'vue/no-v-html': 'off',
      'vue/multi-word-component-names': 'off',
      'vue/require-default-prop': 'off',
      '@typescript-eslint/no-explicit-any': 'off',
      '@typescript-eslint/ban-ts-comment': 'off',

      // Template formatting: this codebase keeps the first attribute on the
      // same line as the tag. The autofix for these rewrites every multi-line
      // element in the repo for no functional gain, so they stay off.
      'vue/first-attribute-linebreak': 'off',
      'vue/max-attributes-per-line': 'off',
      'vue/html-self-closing': 'off',
      'vue/singleline-html-element-content-newline': 'off',
      'vue/html-closing-bracket-newline': 'off',
      'vue/attributes-order': 'off',

      // Header.vue and Footer.vue collide with the HTML element names, but they
      // are long-established here and auto-import resolves them unambiguously.
      'vue/no-reserved-component-names': 'off',

      // The legacy surface still has genuinely unused locals; keep this as a
      // warning so it is visible without blocking the pre-commit hook.
      '@typescript-eslint/no-unused-vars': [
        'warn',
        {argsIgnorePattern: '^_', varsIgnorePattern: '^_'}
      ]
    }
  },
  prettier
)
